version: "3.8"

name: titan-node

services:
  titan-node-pool:
    build: .
    image: titan-node-pool
    container_name: titan-node-pool
    restart: unless-stopped
    runtime: nvidia
    command:
      [
        "-ethAddr",
        "<ETH_ADDRESS>",
        "-nickname",
        "<NICKNAME>",
        "-maxSessions",
        "<MAX_SESSIONS>",
      ]
