version: "3.8"

name: titan-node
#
# If you do not wish to build manually, you can use an image that is rebuilt nightly: icsy7867/titan-node:latest
# 
services:
  titan-node-pool:
    build: .
    image: titan-node-pool
    container_name: titan-node-pool
    restart: unless-stopped
    runtime: nvidia
    environment:
      - "ethAddr=0xXXXXXXXXXX"
      - "nickname=my-nickname"
      - "nvidia=0" # optional
      - "maxSessions=10" # optional
#
# Optional volumes for ensuring logging uses the correct timezone/time
#
    volumes:
      - "/etc/timezone:/etc/timezone:ro" # optional
      - "/etc/localtime:/etc/localtime:ro" #optional
