version: "3.8"

name: titan-node

services:
  titan-node-pool:
    build: .
    image: titan-node-pool
    container_name: titan-node-pool
    restart: unless-stopped
    runtime: nvidia
    environment:
      - "ethAddr=0xXXXXXXXXXX"
      - "nickname=my-nickname"
      - "nvidia=0"
      - "maxSessions=10"
